### ISSUE TITLE
Seasonality Plot Bug

### ISSUE THREAD

**Issue by fionnachalmers** [BHFDSC/cvd-covid-tre-dashboard#15]
Reported that seasonality plot is not loading.

Go to Data Coverage > Seasonality > [Seasonality](https://bhf-dsc-hds.shinyapps.io/cvd-covid-tre-dashboard/#tab-8238-2)
An error has occurred. Check your logs or contact the app author for clarification.

**Comment by LarsMurdock** [comment]
seems to be working

**Comment by LarsMurdock** [comment]
![image](https://github.com/user-attachments/assets/f9e45885-24c3-4e68-84b3-3c006a1dc323)
