### ISSUE TITLE
Loading message

### ISSUE THREAD

**Issue by fionnachalmers** [BHFDSC/cvd-covid-tre-dashboard#2]
The app can take approx 15-30 seconds to load upon launch. Note that loading time is much quicker if another user is on the app. We will look into optimising the code OR using cache that persists across users to speed things up. In the meantime, we explore adding a more appropriate loading message than the default shinyio 'Please wait'

**Comment by LarsMurdock** [comment]
doesn't seem to be that onerous - can come back to it if the load time takes longer or more people complain
