### ISSUE TITLE
Update NHS England Data Dictionary

### ISSUE THREAD

**Issue by fionnachalmers** [BHFDSC/cvd-covid-tre-dashboard#24]

**Comment by LarsMurdock** [comment]
New June 24 dd located and read in..... appears to be structurally similar to the previous so no refactoring needed.

Old covered 122ish tables, vs New which covers 131. The difference appears to the inclusion of iapt subtables. Msds tables have been renamed to 'v2'..... this might have to be addressed in the linkage file to map appropriately.

**Comment by LarsMurdock** [comment]
dd issues related to msds fixed. iapt tbd
