### ISSUE TITLE
iFrame About Us panel blocking use of dashboard

### ISSUE THREAD

**Issue by fionnachalmers** [BHFDSC/cvd-covid-tre-dashboard#29]
![bug](https://github.com/user-attachments/assets/df821fcb-e227-4205-9d2f-2b1c7cd9116b)

**Comment by LarsMurdock** [comment]
Not sure i understand this issue. If you change the zoom (ctrl AND +/- )..... maybe cmd for mac, then you can change the aspect of the iframe banner. Then use the scroll bars to adjust

![image](https://github.com/user-attachments/assets/bc3ba822-8b6f-4675-bbd1-ed1a1d459784)
